# Generated by Django 4.2.3 on 2024-02-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customers_status_delete_completedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.customers')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.orders')),
            ],
        ),
    ]
