# Generated by Django 4.2.3 on 2024-02-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_completedorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedorder',
            old_name='customer',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='completedorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='number',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='order',
            field=models.ManyToManyField(through='api.Orders', to='api.item'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
    ]
