# Generated by Django 4.2.3 on 2024-02-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_customer_completedorder_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='status',
        ),
    ]
