# Generated by Django 4.2.3 on 2024-02-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
