# Generated by Django 4.2.3 on 2024-02-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orders_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
