# Generated by Django 4.2.3 on 2024-02-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_orders_is_deleted_item_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='orders',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
    ]
