# Generated by Django 4.2.3 on 2024-02-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_item_is_deleted_orders_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='completed',
        ),
        migrations.AddField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
