# Generated by Django 4.2.3 on 2024-02-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_orders_completed_item_completed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('customer', 'product')},
        ),
    ]
