# Generated by Django 4.2.3 on 2024-02-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orders_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='item_id',
        ),
    ]
