# Generated by Django 4.2.3 on 2024-02-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_item_item_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='product_id',
        ),
    ]
