# Generated by Django 4.2.3 on 2024-02-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_item_id_item_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.customers'),
        ),
    ]
