# Generated by Django 4.2.3 on 2024-02-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_info_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
